-- FitFlow Additional Exercises Seed
-- Run this after migration_v5.sql to add more exercises
-- Uses reliable image URLs from Unsplash

USE fitflow;

-- ============================================
-- ADDITIONAL STRENGTH EXERCISES
-- ============================================

-- More Chest Exercises
INSERT INTO exercises (name, description, category, muscle_group, equipment, difficulty, instructions, image_url) VALUES
('Decline Bench Press', 'Targets lower chest using decline angle', 'strength', 'Chest', 'Barbell', 'intermediate', '1. Set bench to decline angle\n2. Unrack bar with shoulder-width grip\n3. Lower bar to lower chest\n4. Press up to starting position', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Close Grip Bench Press', 'Chest and tricep focused pressing', 'strength', 'Chest', 'Barbell', 'intermediate', '1. Lie on flat bench\n2. Grip bar with hands shoulder-width apart\n3. Lower bar to lower chest\n4. Press up keeping elbows tucked', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Chest Dips', 'Bodyweight exercise for lower chest', 'bodyweight', 'Chest', 'Dip Bars', 'intermediate', '1. Grip parallel bars\n2. Lean forward slightly\n3. Lower until stretch in chest\n4. Push back up', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Landmine Press', 'Angled pressing for shoulders and chest', 'strength', 'Chest', 'Barbell', 'beginner', '1. Place barbell end in corner or landmine\n2. Hold other end at chest\n3. Press up and forward\n4. Lower with control', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),
('Machine Chest Press', 'Beginner-friendly pressing machine', 'machine', 'Chest', 'Chest Press Machine', 'beginner', '1. Adjust seat height\n2. Grip handles at chest level\n3. Press forward\n4. Return with control', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),

-- More Back Exercises
('T-Bar Row', 'Compound rowing for back thickness', 'strength', 'Back', 'T-Bar', 'intermediate', '1. Straddle the bar\n2. Bend at hips, grip handle\n3. Pull bar to chest\n4. Lower with control', 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=400'),
('Single Arm Dumbbell Row', 'Unilateral back exercise', 'strength', 'Back', 'Dumbbells', 'beginner', '1. Place knee and hand on bench\n2. Row dumbbell to hip\n3. Squeeze shoulder blade\n4. Lower with control', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400'),
('Chest Supported Row', 'Strict rowing without lower back stress', 'strength', 'Back', 'Dumbbells', 'beginner', '1. Lie face down on incline bench\n2. Let arms hang with dumbbells\n3. Row to sides of chest\n4. Lower with control', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400'),
('Straight Arm Pulldown', 'Lat isolation exercise', 'strength', 'Back', 'Cable Machine', 'beginner', '1. Stand at cable with bar\n2. Keep arms straight\n3. Pull bar down to thighs\n4. Control the return', 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400'),
('Chin-ups', 'Underhand grip pull-up for back and biceps', 'bodyweight', 'Back', 'Pull-up Bar', 'intermediate', '1. Hang with underhand grip\n2. Pull chin over bar\n3. Squeeze at top\n4. Lower with control', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Inverted Rows', 'Bodyweight horizontal pulling', 'bodyweight', 'Back', 'Barbell', 'beginner', '1. Set bar at hip height\n2. Hang underneath with feet forward\n3. Pull chest to bar\n4. Lower with control', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Meadows Row', 'Single arm landmine row variation', 'strength', 'Back', 'Barbell', 'advanced', '1. Stand perpendicular to landmine\n2. Staggered stance, grip end of bar\n3. Row explosively to hip\n4. Control the negative', 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=400'),

-- More Shoulder Exercises
('Seated Dumbbell Press', 'Overhead pressing with back support', 'strength', 'Shoulders', 'Dumbbells', 'beginner', '1. Sit with back supported\n2. Hold dumbbells at shoulders\n3. Press overhead\n4. Lower with control', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400'),
('Front Raises', 'Isolation for front deltoids', 'strength', 'Shoulders', 'Dumbbells', 'beginner', '1. Stand with dumbbells at thighs\n2. Raise arms forward to shoulder height\n3. Keep slight bend in elbows\n4. Lower with control', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400'),
('Rear Delt Flyes', 'Isolation for posterior deltoids', 'strength', 'Shoulders', 'Dumbbells', 'beginner', '1. Bend at hips, torso parallel to floor\n2. Raise arms out to sides\n3. Squeeze shoulder blades\n4. Lower with control', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400'),
('Upright Rows', 'Compound for shoulders and traps', 'strength', 'Shoulders', 'Barbell', 'intermediate', '1. Hold bar at thighs\n2. Pull bar up along body\n3. Lead with elbows\n4. Lower with control', 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400'),
('Machine Shoulder Press', 'Guided overhead pressing', 'machine', 'Shoulders', 'Shoulder Press Machine', 'beginner', '1. Adjust seat height\n2. Grip handles at shoulder level\n3. Press overhead\n4. Lower with control', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),
('Cable Lateral Raises', 'Constant tension lateral raises', 'strength', 'Shoulders', 'Cable Machine', 'beginner', '1. Stand next to low cable\n2. Raise arm out to side\n3. Stop at shoulder height\n4. Lower with control', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),
('Pike Push-ups', 'Bodyweight shoulder pressing', 'bodyweight', 'Shoulders', 'None', 'intermediate', '1. Start in downward dog position\n2. Bend elbows, lower head toward floor\n3. Push back up\n4. Keep hips high throughout', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),

-- More Arm Exercises
('Preacher Curls', 'Strict bicep isolation', 'strength', 'Biceps', 'EZ Bar', 'beginner', '1. Sit at preacher bench\n2. Rest arms on pad\n3. Curl bar up\n4. Lower with control', 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=400'),
('Concentration Curls', 'Single arm bicep isolation', 'strength', 'Biceps', 'Dumbbells', 'beginner', '1. Sit with elbow on inner thigh\n2. Curl dumbbell up\n3. Squeeze at top\n4. Lower slowly', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400'),
('Incline Dumbbell Curls', 'Long head bicep emphasis', 'strength', 'Biceps', 'Dumbbells', 'intermediate', '1. Lie on incline bench\n2. Let arms hang straight\n3. Curl up without moving upper arms\n4. Lower with control', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400'),
('Cable Curls', 'Constant tension bicep exercise', 'strength', 'Biceps', 'Cable Machine', 'beginner', '1. Stand at low cable\n2. Curl bar up\n3. Squeeze at top\n4. Lower with control', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),
('Overhead Tricep Extension', 'Long head tricep focus', 'strength', 'Triceps', 'Dumbbells', 'beginner', '1. Hold dumbbell overhead with both hands\n2. Lower behind head\n3. Keep elbows pointing up\n4. Extend back up', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400'),
('Tricep Kickbacks', 'Tricep isolation exercise', 'strength', 'Triceps', 'Dumbbells', 'beginner', '1. Bend forward at hips\n2. Keep upper arm parallel to floor\n3. Extend forearm back\n4. Squeeze and return', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400'),
('Close Grip Push-ups', 'Bodyweight tricep exercise', 'bodyweight', 'Triceps', 'None', 'beginner', '1. Place hands close together\n2. Lower chest to hands\n3. Keep elbows close to body\n4. Push back up', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Diamond Push-ups', 'Advanced tricep push-up variation', 'bodyweight', 'Triceps', 'None', 'intermediate', '1. Form diamond with hands\n2. Lower chest to hands\n3. Keep core tight\n4. Push back up', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Wrist Curls', 'Forearm strengthening', 'strength', 'Forearms', 'Barbell', 'beginner', '1. Sit with forearms on thighs\n2. Curl wrists up\n3. Lower slowly\n4. Keep forearms stationary', 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=400'),
('Reverse Curls', 'Forearm and brachialis focus', 'strength', 'Forearms', 'Barbell', 'beginner', '1. Hold bar with overhand grip\n2. Curl bar up\n3. Keep elbows at sides\n4. Lower with control', 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=400'),

-- More Leg Exercises
('Front Squat', 'Quad-focused squat variation', 'strength', 'Quadriceps', 'Barbell', 'advanced', '1. Rest bar on front shoulders\n2. Cross arms or use clean grip\n3. Squat down keeping torso upright\n4. Drive up through heels', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),
('Bulgarian Split Squat', 'Unilateral leg exercise', 'strength', 'Legs', 'Dumbbells', 'intermediate', '1. Rear foot elevated on bench\n2. Lower into lunge\n3. Keep front knee over ankle\n4. Push back up', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),
('Goblet Squat', 'Beginner-friendly weighted squat', 'strength', 'Legs', 'Dumbbell', 'beginner', '1. Hold dumbbell at chest\n2. Squat down between legs\n3. Keep chest up\n4. Stand back up', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),
('Sumo Deadlift', 'Wide stance deadlift variation', 'strength', 'Legs', 'Barbell', 'intermediate', '1. Wide stance, toes pointed out\n2. Grip bar between legs\n3. Drive through heels\n4. Lock out at top', 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400'),
('Hip Thrust', 'Glute-focused hip extension', 'strength', 'Glutes', 'Barbell', 'intermediate', '1. Upper back on bench\n2. Bar across hips\n3. Drive hips up\n4. Squeeze glutes at top', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),
('Glute Bridge', 'Bodyweight glute activation', 'bodyweight', 'Glutes', 'None', 'beginner', '1. Lie on back, knees bent\n2. Drive hips up\n3. Squeeze glutes at top\n4. Lower with control', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Step Ups', 'Unilateral leg exercise', 'strength', 'Legs', 'Plyo Box', 'beginner', '1. Stand facing box\n2. Step up with one leg\n3. Drive through heel\n4. Step down with control', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Walking Lunges', 'Dynamic lunge variation', 'strength', 'Legs', 'Dumbbells', 'beginner', '1. Hold dumbbells at sides\n2. Step forward into lunge\n3. Push off front foot\n4. Step into next lunge', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),
('Sissy Squat', 'Advanced quad isolation', 'bodyweight', 'Quadriceps', 'None', 'advanced', '1. Hold onto support\n2. Rise onto toes, lean back\n3. Lower knees forward\n4. Push back up', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),
('Nordic Curls', 'Eccentric hamstring exercise', 'bodyweight', 'Hamstrings', 'None', 'advanced', '1. Kneel with ankles secured\n2. Lower body forward slowly\n3. Catch yourself at bottom\n4. Push back up or use assistance', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Seated Calf Raises', 'Soleus-focused calf exercise', 'machine', 'Calves', 'Seated Calf Machine', 'beginner', '1. Sit with pad on thighs\n2. Rise up on toes\n3. Pause at top\n4. Lower slowly', 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400'),
('Donkey Calf Raises', 'Loaded calf stretch and contraction', 'strength', 'Calves', 'Weight Belt', 'intermediate', '1. Bend at hips, hold onto support\n2. Rise up on toes\n3. Full stretch at bottom\n4. Squeeze at top', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400'),

-- More Core Exercises
('Russian Twists', 'Rotational core exercise', 'bodyweight', 'Core', 'None', 'beginner', '1. Sit with knees bent, lean back\n2. Hold hands together\n3. Rotate side to side\n4. Keep core engaged', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Bicycle Crunches', 'Dynamic ab exercise', 'bodyweight', 'Core', 'None', 'beginner', '1. Lie on back, hands behind head\n2. Bring elbow to opposite knee\n3. Alternate sides\n4. Keep lower back pressed down', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400'),
('Dead Bug', 'Core stability exercise', 'bodyweight', 'Core', 'None', 'beginner', '1. Lie on back, arms and legs up\n2. Lower opposite arm and leg\n3. Keep lower back flat\n4. Alternate sides', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400'),
('Pallof Press', 'Anti-rotation core exercise', 'strength', 'Core', 'Cable Machine', 'intermediate', '1. Stand sideways to cable\n2. Hold handle at chest\n3. Press out and hold\n4. Resist rotation', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),
('Ab Rollouts', 'Advanced core exercise', 'bodyweight', 'Core', 'Ab Wheel', 'advanced', '1. Kneel with hands on wheel\n2. Roll forward slowly\n3. Extend as far as possible\n4. Roll back to start', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('V-Ups', 'Dynamic full ab exercise', 'bodyweight', 'Core', 'None', 'intermediate', '1. Lie flat on back\n2. Lift legs and torso together\n3. Touch toes at top\n4. Lower with control', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400'),
('Side Plank', 'Oblique stability exercise', 'bodyweight', 'Core', 'None', 'beginner', '1. Lie on side, elbow under shoulder\n2. Lift hips off ground\n3. Keep body in straight line\n4. Hold position', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400'),
('Wood Chops', 'Rotational power exercise', 'strength', 'Core', 'Cable Machine', 'intermediate', '1. Set cable high\n2. Pull diagonally across body\n3. Rotate through core\n4. Control the return', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'),
('Dragon Flags', 'Advanced bodyweight core exercise', 'bodyweight', 'Core', 'Flat Bench', 'advanced', '1. Lie on bench, grip behind head\n2. Lift body as one unit\n3. Lower slowly with control\n4. Keep body straight', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400'),
('Toe Touches', 'Upper ab focused exercise', 'bodyweight', 'Core', 'None', 'beginner', '1. Lie on back, legs vertical\n2. Reach up to touch toes\n3. Lift shoulder blades off floor\n4. Lower with control', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400'),

-- ============================================
-- ADDITIONAL CARDIO EXERCISES
-- ============================================
('Stair Climbing', 'Cardio using stairs or machine', 'cardio', 'Legs', 'Stair Climber', 'beginner', '1. Step onto machine or stairs\n2. Climb at steady pace\n3. Use handrails lightly\n4. Maintain rhythm', 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=400'),
('Battle Ropes', 'Full body conditioning', 'cardio', 'Full Body', 'Battle Ropes', 'intermediate', '1. Hold rope ends in each hand\n2. Create waves by alternating arms\n3. Keep core engaged\n4. Maintain consistent rhythm', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Box Jumps', 'Plyometric leg exercise', 'cardio', 'Legs', 'Plyo Box', 'intermediate', '1. Stand facing box\n2. Jump up onto box\n3. Land softly with bent knees\n4. Step down and repeat', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Sprints', 'High intensity running intervals', 'cardio', 'Full Body', 'None', 'intermediate', '1. Warm up thoroughly\n2. Sprint at maximum effort\n3. Rest between intervals\n4. Repeat for desired sets', 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=400'),
('Sled Push', 'Full body conditioning', 'cardio', 'Full Body', 'Sled', 'intermediate', '1. Grip sled handles low\n2. Drive through legs\n3. Keep core tight\n4. Push for distance or time', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Assault Bike', 'Full body cardio machine', 'cardio', 'Full Body', 'Assault Bike', 'beginner', '1. Sit on bike, grip handles\n2. Pedal and push/pull arms\n3. Maintain steady pace\n4. Increase intensity as needed', 'https://images.unsplash.com/photo-1517649763962-0a6cb0167c73?w=400'),
('Ski Erg', 'Upper body dominant cardio', 'cardio', 'Full Body', 'Ski Erg', 'intermediate', '1. Stand at machine, grip handles\n2. Pull down in skiing motion\n3. Hinge at hips\n4. Return handles up', 'https://images.unsplash.com/photo-1519505907962-0a6cb0167c73?w=400'),
('Burpee Box Jumps', 'Combined plyometric exercise', 'cardio', 'Full Body', 'Plyo Box', 'advanced', '1. Do a burpee\n2. Jump onto box\n3. Step down\n4. Repeat', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Kettlebell Swings', 'Hip hinge cardio exercise', 'cardio', 'Full Body', 'Kettlebells', 'beginner', '1. Stand with kettlebell between feet\n2. Hinge and swing back\n3. Drive hips forward\n4. Swing to chest height', 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400'),
('Bear Crawls', 'Full body locomotion', 'cardio', 'Full Body', 'None', 'beginner', '1. Start on hands and knees\n2. Lift knees slightly\n3. Move opposite hand and foot\n4. Keep hips low', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Jumping Lunges', 'Plyometric lunge variation', 'cardio', 'Legs', 'None', 'intermediate', '1. Start in lunge position\n2. Jump and switch legs\n3. Land softly\n4. Repeat alternating', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Skaters', 'Lateral plyometric exercise', 'cardio', 'Legs', 'None', 'beginner', '1. Jump laterally\n2. Land on one foot\n3. Swing other leg behind\n4. Jump to other side', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'),
('Outdoor Running', 'Traditional running outdoors', 'cardio', 'Full Body', 'None', 'beginner', '1. Start at comfortable pace\n2. Maintain good posture\n3. Land midfoot\n4. Breathe rhythmically', 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=400'),

-- ============================================
-- ADDITIONAL FLEXIBILITY EXERCISES
-- ============================================
('Pigeon Pose', 'Deep hip opener stretch', 'flexibility', 'Hip Flexors', 'Yoga Mat', 'intermediate', '1. Start in plank\n2. Bring one knee forward\n3. Lower hips toward floor\n4. Hold and breathe', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Downward Dog', 'Full body stretch and strength', 'flexibility', 'Full Body', 'Yoga Mat', 'beginner', '1. Start on hands and knees\n2. Lift hips up and back\n3. Push heels toward floor\n4. Keep arms straight', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Cobra Stretch', 'Spinal extension stretch', 'flexibility', 'Back', 'Yoga Mat', 'beginner', '1. Lie face down\n2. Place hands under shoulders\n3. Press up, arching back\n4. Keep hips on floor', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Child\'s Pose', 'Relaxing back and hip stretch', 'flexibility', 'Back', 'Yoga Mat', 'beginner', '1. Kneel on floor\n2. Sit back on heels\n3. Reach arms forward\n4. Rest forehead on floor', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Quad Stretch', 'Standing quadricep stretch', 'flexibility', 'Quadriceps', 'None', 'beginner', '1. Stand on one leg\n2. Pull foot to glute\n3. Keep knees together\n4. Hold and balance', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Calf Stretch', 'Wall-assisted calf stretch', 'flexibility', 'Calves', 'None', 'beginner', '1. Face wall, hands on wall\n2. Step one foot back\n3. Keep heel on floor\n4. Lean into wall', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Tricep Stretch', 'Overhead arm stretch', 'flexibility', 'Triceps', 'None', 'beginner', '1. Raise arm overhead\n2. Bend elbow behind head\n3. Use other hand to pull\n4. Hold stretch', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Lat Stretch', 'Kneeling side stretch', 'flexibility', 'Back', 'None', 'beginner', '1. Kneel and reach arm overhead\n2. Lean to opposite side\n3. Feel stretch in lat\n4. Hold and breathe', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Butterfly Stretch', 'Inner thigh and hip stretch', 'flexibility', 'Hip Flexors', 'Yoga Mat', 'beginner', '1. Sit with soles of feet together\n2. Hold ankles\n3. Press knees toward floor\n4. Lean forward gently', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Figure Four Stretch', 'Glute and hip stretch', 'flexibility', 'Glutes', 'Yoga Mat', 'beginner', '1. Lie on back\n2. Cross ankle over knee\n3. Pull thigh toward chest\n4. Hold stretch', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Neck Rolls', 'Gentle neck mobility', 'flexibility', 'Neck', 'None', 'beginner', '1. Sit or stand tall\n2. Drop chin to chest\n3. Roll head in circle\n4. Reverse direction', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Wrist Circles', 'Wrist mobility exercise', 'flexibility', 'Forearms', 'None', 'beginner', '1. Extend arms forward\n2. Make fists\n3. Circle wrists slowly\n4. Reverse direction', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Ankle Circles', 'Ankle mobility exercise', 'flexibility', 'Calves', 'None', 'beginner', '1. Sit or stand on one leg\n2. Circle ankle\n3. Move through full range\n4. Reverse direction', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Thoracic Rotation', 'Upper back mobility', 'flexibility', 'Back', 'Yoga Mat', 'beginner', '1. Start on hands and knees\n2. Place one hand behind head\n3. Rotate toward that side\n4. Return and repeat', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Standing Forward Fold', 'Hamstring and back stretch', 'flexibility', 'Hamstrings', 'None', 'beginner', '1. Stand with feet together\n2. Hinge at hips\n3. Reach toward floor\n4. Let head hang', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Supine Twist', 'Spinal rotation stretch', 'flexibility', 'Back', 'Yoga Mat', 'beginner', '1. Lie on back\n2. Bring knees to chest\n3. Drop knees to one side\n4. Keep shoulders flat', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('Thread the Needle', 'Shoulder and thoracic stretch', 'flexibility', 'Shoulders', 'Yoga Mat', 'beginner', '1. Start on hands and knees\n2. Thread one arm under body\n3. Rest shoulder on floor\n4. Hold and breathe', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'),
('World\'s Greatest Stretch', 'Full body mobility', 'flexibility', 'Full Body', 'None', 'intermediate', '1. Lunge forward\n2. Place hand on floor\n3. Rotate and reach up\n4. Alternate sides', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400');
